import { px } from "@zos/utils";
import { align } from "@zos/ui";

export const TITLE = { x: px(40), y: px(24), w: px(310), h: px(34), color: 0xffffff, text_size: px(26), align_h: align.CENTER_H };
export const BACK = { x: px(10), y: px(24), w: px(60), h: px(34), color: 0xada79c, text_size: px(17) };
export const GRID_X = px(15);
export const GRID_Y = px(70);
export const CARD_W = px(110);
export const CARD_H = px(130);
export const CARD_GAP = px(15);
export const IMG_W = px(56);
export const IMG_H = px(56);
export const LABEL_Y = px(15);
export const COUNT_Y = px(85);
export const IMG_Y = px(40);
export const TEXT_COLOR = 0xffffff;
export const COUNT_COLOR = 0x91d1b2;
export const BG_COLOR = 0x1c2528;
export const TEXT_SIZE_NAME = 15;
export const TEXT_SIZE_COUNT = 13;
